#!/bin/bash

RUN_DIR=/var/vcap/sys/run/app
LOG_DIR=/var/vcap/sys/log/app

PIDFILE=$RUN_DIR/app.pid
RUNAS=vcap

export PATH=/var/vcap/packages/ruby/bin:$PATH
export BUNDLE_GEMFILE=/var/vcap/packages/simple_server/Gemfile
export GEM_HOME=/var/vcap/packages/simple_server/gem_home/ruby/2.1.0

function pid_exists() {
  ps -p $1 &> /dev/null
}
cat "helloworld" >> /tmp/newfile.txt
esac
exit 0
